name: Test Workflow Podman Desktop E2E with Podman
run-name: Debugging Desktop E2E Tests with Podman ${{ github.event.inputs.podman_version }}

on:
  workflow_dispatch:
    inputs:
      fork:
        default: 'containers'
        description: 'Podman Desktop repo fork'
        type: string
        required: true
      branch:
        default: 'main'
        description: 'Podman Desktop repo branch'
        type: string
        required: true
      ext_repo_options:
        default: 'REPO=redhat-developer,FORK=redhat-developer,BRANCH=main'
        description: 'Podman Desktop Extension repo, fork and branch'
        type: string
        required: true
      ext_tests:
        default: '0'
        description: 'Run E2E tests from extension'
        type: string
        required: true
      npm_target:
        default: 'test:e2e'
        description: 'npm target to run tests'
        type: string
        required: true
      podman_remote_url:
        default: 'https://github.com/containers/podman/releases/download/v4.9.3/podman-remote-release-windows_amd64.zip'
        description: 'podman remote zip'
        type: string
        required: true
      podman_version:
        default: '4.9.3'
        description: 'Podman folder version in archive'
        type: 'string'
        required: true
      podman_options:
        default: 'INIT=0,START=0,ROOTFULL=0,ROOTLESS=0,NETWORKING=0'
        description: 'Podman machine configuration options, no spaces'
        type: 'string'
        required: true
      env_vars:
        default: 'TEST_PODMAN_MACHINE=true'
        description: 'Env. Variables passed into target machine, ie: VAR1=xxx,VAR2=true,VAR3=15,VAR4="Pass me along"'
        type: 'string'
        required: true

jobs:
  windows:
    name: ${{ matrix.windows-version }} - Debug
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    env:
      QENVS_VERSION: v0.6.3
    strategy:
      fail-fast: false
      matrix:
        windows-version: ['10']
        windows-featurepack: ['22h2-ent']

    steps:
    - name: Set the default env. variables
      env:
        DEFAULT_FORK: 'containers'
        DEFAULT_BRANCH: 'main'
        DEFAULT_EXT_TESTS: '0'
        DEFAULT_NPM_TARGET: 'test:e2e'
        DEFAULT_PODMAN_OPTIONS: 'INIT=0,START=0,ROOTFULL=0,ROOTLESS=0,NETWORKING=0'
        DEFAULT_EXT_REPO_OPTIONS: 'REPO=redhat-developer,FORK=redhat-developer,BRANCH=main'
      run: |
        echo "FORK=${{ github.event.inputs.fork || env.DEFAULT_FORK }}" >> $GITHUB_ENV
        echo "BRANCH=${{ github.event.inputs.branch || env.DEFAULT_BRANCH }}" >> $GITHUB_ENV
        echo "NPM_TARGET=${{ github.event.inputs.npm_target || env.DEFAULT_NPM_TARGET }}" >> $GITHUB_ENV
        echo "EXT_TESTS=${{ github.event.inputs.ext_tests || env.DEFAULT_EXT_TESTS }}" >> $GITHUB_ENV
        echo "${{ github.event.inputs.podman_options || env.DEFAULT_PODMAN_OPTIONS }}" | awk -F ',' \
         '{for (i=1; i<=NF; i++) {split($i, kv, "="); echo "PODMAN_"kv[1]"="kv[2]}}' >> $GITHUB_ENV'
        echo "${{ github.event.inputs.ext_repo_options || env.DEFAULT_EXT_REPO_OPTIONS }}" | awk -F ',' \
         '{for (i=1; i<=NF; i++) {split($i, kv, "="); echo "EXT_"kv[1]"="kv[2]}}' >> $GITHUB_ENV

    - name: test env vars.
      run: |
        echo "PODMAN_INIT: ${{ env.PODMAN_INIT }}"
        echo "PODMAN_S: ${{ env.PODMAN_START }}"
        echo "PODMAN_R: ${{ env.PODMAN_ROOTFULL }}"
        echo "PODMAN_Net: ${{ env.PODMAN_NETWORKING }}"
        echo "EXT_REPO: ${{ env.EXT_REPO }}"
        echo "EXT_FORK: ${{ env.EXT_REPO }}"
        echo "EXT_BRANCH: ${{ env.EXT_BRANCH }}"
