# Idea of this Mac based workflows is as follows:
# Main job (this one), controlls the schedulling of the associated jobs. 
# It also creates an initial request for a host machine on AWS and grants the access to the machine to the particular jobs.
# Associated jobs has their own scheduller that must be agreed upon outside of this job. 
# Once the external job is started, it requires this job to get access to the secrets require to connect to the machine using qenvs project
# At the end of the day, another schedulled trigger runs a clean up job that will destroy the instance and free up resources.

# Questions
# 1. Should we rely on providing a concrete time frames to a various jobs/teams to make use of the machine?
# 2. Jobs could be run in a sequence, one after another. Every job would need to have a timeout set so we can execute all in 24 hours
# 3. How can we make use of an access information if the jobs are done and we still have a dedicated time on the machine?
# 4. What teams to include? This sound like totally different project/repo


# Solution of passing secrets is based on https://github.com/orgs/community/discussions/13082

name: Mac Workflow

# env:
#   CRON_START: '1 10 * * 4' # “At 10:01 on Thursday.”
#   CRON_END: '10 10 * * 4' # “At 10:10 on Thursday.”

# on:
#   schedule: 
#   - cron: '1 10 * * 4' # “At 10:01 on Thursday.”
#   - cron: '10 10 * * 4' # “At 10:10 on Thursday.”

on:
  workflow_dispatch:

jobs:
  startJob:
    runs-on: ubuntu-latest
    # if: ${{ github.event_name == 'schedule' && github.event.inputs.cron == ${{ env.CRON_START }} }}

    outputs:
      HOST: ${{ steps.set_secret.outputs.HOST }}
      KEY: ${{ steps.set_secret.outputs.KEY }}
    
    steps:
      - name: Create an instance on AWS
        run: echo "Creating an instance here..."

      - name: Output encoded secrets
        id: set_secret
        # env:
        #   HOST: ${{ secrets.HOST }}
        #   KEY: ${{ secrets.KEY }}
        run: |
          host=$(echo HOST_SECRET | base64 -w0 | base64 -w0)
          key=$(echo KEY_SECRET | base64 -w0 | base64 -w0)
          echo "host is $host"
          echo "HOST=$host" >> $GITHUB_OUTPUT
          echo "key is: $key"
          echo "KEY=$key" >> $GITHUB_OUTPUT

  smokeJob: 
    uses: ./.github/workflows/mac-smoke-test.yaml
    needs: startJob
    secrets:
      env_vars: |
        HOST=${{ needs.startJob.outputs.HOST }}
        KEY=${{ needs.startJob.outputs.KEY }}

  e2eJob: 
    uses: ./.github/workflows/mac-e2e-test.yaml
    needs: startJob
    secrets:
      env_vars: |
        HOST=${{ needs.startJob.outputs.HOST }}
        KEY=${{ needs.startJob.outputs.KEY }}

  finalJob:
    runs-on: ubuntu-latest
    needs: [startJob, smokeJob, e2eJob]
    env:
      env_vars: |
        host: ${{ needs.startJob.outputs.host }}
        key: ${{ needs.starJob.outputs.key }}
    # if: ${{ github.event_name == 'schedule' && github.event.inputs.cron == ${{ env.CRON_END }} }}

    outputs:
      host: ${{ steps.startJob.outputs.host }}
      key: ${{ steps.startJob.outputs.key }}

    steps:
      - name: Running Clean up Action
        run: |
          echo "Final job is running with HOST=${{ needs.startJob.outputs.host }}"
          echo "Final job is running with KEY=${{ needs.startJob.outputs.key }}"
          echo "Bye bye"

