name: Debugging workflow

on:
  schedule:
    - cron:  '*/3 * * * *'
  workflow_dispatch:
    inputs:
      fork:
        default: 'containers'
        description: 'Podman Desktop repo fork'
        type: string
        required: true
      branch:
        default: 'main'
        description: 'Podman Desktop repo branch'
        type: string
        required: true
      npm_target:
        default: 'test:e2e'
        description: 'npm target to run tests'
        type: string
        required: true
      env_vars:
        default: 'TEST_PODMAN_MACHINE=true'
        description: 'Env. Variables passed into target machine'
        type: 'string'
        required: true
      debug:
        description: 'For debugging to restrict what is run'
        type: choice
        options:
          - 'false'
          - 'true'

jobs:
  windows:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    env:
      MAPT_VERSION: v0.6.8
      MAPT_IMAGE: quay.io/redhat-developer/mapt
    strategy:
      fail-fast: false
      matrix:
        windows-version: ['10','11']
        windows-featurepack: ['22h2-ent', '23h2-ent']
        exclude:
        - windows-version: '10'
          windows-featurepack: '23h2-ent'
        - windows-version: '11'
          windows-featurepack: '22h2-ent'
        - windows-version: ${{ (github.event.inputs.debug && github.event.inputs.debug == 'true') && '11' || 'N/A' }}
          windows-featurepack: ${{ (github.event.inputs.debug && github.event.inputs.debug == 'true') && '23h2-ent' || 'N/A' }}

    steps:
    - name: Set the default env. variables
      env:
        DEFAULT_FORK: 'containers'
        DEFAULT_BRANCH: 'main'
        DEFAULT_NPM_TARGET: 'test:e2e'
        DEFAULT_ENV_VARS: 'TEST_PODMAN_MACHINE=true'
        DEFAULT_PODMAN_OPTIONS: 'INIT=1,START=1,ROOTFUL=1,NETWORKING=0'
      run: |
        echo "FORK=${{ github.event.inputs.fork || env.DEFAULT_FORK }}" >> $GITHUB_ENV
        echo "BRANCH=${{ github.event.inputs.branch || env.DEFAULT_BRANCH }}" >> $GITHUB_ENV
        echo "NPM_TARGET=${{ github.event.inputs.npm_target || env.DEFAULT_NPM_TARGET }}" >> $GITHUB_ENV
        echo "ENV_VARS=${{ github.event.inputs.env_vars || env.DEFAULT_ENV_VARS }}" >> $GITHUB_ENV
        echo "${{ env.DEFAULT_PODMAN_OPTIONS }}" | awk -F ',' \
         '{for (i=1; i<=NF; i++) {split($i, kv, "="); print "PODMAN_"kv[1]"="kv[2]}}' >> $GITHUB_ENV

    - name: Conditional step
      if: ${{ !github.event.inputs.debug || github.event.inputs.debug == 'false' }}
      run: echo "I AM RUNNING! ${{ github.event.inputs.debug }}"
